# Generated by Django 2.1.7 on 2019-04-17 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0004_auto_20190413_2135'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='is_recognized',
            field=models.CharField(default='in_progress', max_length=40),
        ),
        migrations.AddField(
            model_name='user',
            name='is_recognized',
            field=models.CharField(default='in_progress', max_length=40),
        ),
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
