# Generated by Django 2.1.7 on 2019-04-21 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0006_auto_20190421_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='neutral',
            field=models.CharField(default='unknown', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('reply', 'Reply'), ('notice', 'Notice')], max_length=30, null=True),
        ),
    ]
