# Generated by Django 2.1.7 on 2019-05-01 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0013_auto_20190430_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleimage',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aricleImages', to='midgo_app.Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('psychology', 'psychology'), ('veterinary_medicine', 'veterinary_medicine'), ('nutrition', 'nutrition')], default='veterinary_medicine', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('reply', 'Reply'), ('notice', 'Notice')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=30, null=True),
        ),
    ]
