# Generated by Django 2.1.7 on 2019-05-01 13:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0014_auto_20190501_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='article_notifications', to='midgo_app.Article'),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('veterinary_medicine', 'veterinary_medicine'), ('psychology', 'psychology'), ('nutrition', 'nutrition')], default='veterinary_medicine', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Silver', 'Silver'), ('Gold', 'Gold')], max_length=30, null=True),
        ),
    ]
