# Generated by Django 2.1.7 on 2019-05-02 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0015_auto_20190501_2213'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='recomment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('veterinary_medicine', 'veterinary_medicine'), ('nutrition', 'nutrition'), ('psychology', 'psychology')], default='veterinary_medicine', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Comments', to='midgo_app.Article'),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Recomments', to='midgo_app.Comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Silver', 'Silver'), ('Bronze', 'Bronze')], max_length=30, null=True),
        ),
    ]
