# Generated by Django 2.1.7 on 2019-05-02 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0016_auto_20190502_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('nutrition', 'nutrition'), ('psychology', 'psychology'), ('veterinary_medicine', 'veterinary_medicine')], default='veterinary_medicine', max_length=20),
        ),
    ]
