# Generated by Django 2.1.7 on 2019-05-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0017_auto_20190502_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('veterinary_medicine', 'veterinary_medicine'), ('psychology', 'psychology'), ('nutrition', 'nutrition')], default='veterinary_medicine', max_length=20),
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('notice', 'Notice'), ('reply', 'Reply')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Bronze', 'Bronze')], max_length=30, null=True),
        ),
    ]
