# Generated by Django 2.1.7 on 2019-05-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0018_auto_20190502_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterModelOptions(
            name='recomment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('reply', 'Reply'), ('notice', 'Notice')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('Bronze', 'Bronze'), ('Gold', 'Gold'), ('Silver', 'Silver')], max_length=30, null=True),
        ),
    ]
