# Generated by Django 2.1.7 on 2019-05-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0019_auto_20190502_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('nutrition', 'nutrition'), ('psychology', 'psychology'), ('veterinary_medicine', 'veterinary_medicine')], default='veterinary_medicine', max_length=20),
        ),
        migrations.AlterField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='midgo_app.Article'),
        ),
        migrations.AlterField(
            model_name='recomment',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recomments', to='midgo_app.Comment'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('Gold', 'Gold'), ('Bronze', 'Bronze'), ('Silver', 'Silver')], max_length=30, null=True),
        ),
    ]
