# Generated by Django 2.1.7 on 2019-05-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('midgo_app', '0021_auto_20190502_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('nutrition', 'nutrition'), ('psychology', 'psychology'), ('veterinary_medicine', 'veterinary_medicine')], default='veterinary_medicine', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Bronze', 'Bronze')], max_length=30, null=True),
        ),
    ]
